#!/bin/bash
#
# uka1
#

cd ~
cd ..
cd ..
cd var
cd public
cd unix
cd uka1
cd ccattell
cp README ~/src/unix/projects
cp uka1.pptx ~/src/unix/projects
cd ~
cd src
cd unix
cd projects
mkdir uka5
mv README uka1
mv uka1.pptx uka1
cd uka1
bzip2 -d uka1.pptx
cp uka1.pptx.out uka1.tar
tar -xf uka1.tar
cat datafile | head -16 > half1
cat datafile | tail -16 > half2
cat half1 | tr -d X > h1
cat half2 | tr -d X > h2
cat h2 | rev > h2rev
cat h2rev h1 > wholeN
cat wholeN | cut -c 1-38 > righthalf
cat wholeN | cut -c 39-90 > lefthalf
paste -dX lefthalf righthalf > wholeX
sed -i '/^$/d' whole
cat whole





#cat h1 | cut c 44- > q3
#cat h1 | cut -c -34 > q4
#cat h2rev | cut -c -34 > q2
#cat h2rev | cut -c 44- > q1
#paste -dX q3 q4 > bottomhalf
#paste -dX q1 q2 > tophalf
#cat tophalf bottomhalf > wholeX
#cat wholeX | tr -d X > whole

