#!/bin/bash
#
#

mkdir ~/src/unix/projects/uka0
cp /var/public/unix/uka0/ccattell/README ~/src/unix/projects/uka0/README
cp /var/public/unix/uka0/ccattell/uka0.bas ~/src/unix/projects/uka0/uka0.bas
cd ~/src/unix/projects/uka0
cp uka0.bas uka0.xz
unxz uka0.xz
unzip uka0
cat datafile | cut -c 1-39 > lefthalf
cat datafile | cut -c 41- > righthalf
cat lefthalf | tail -n 15 | rev > q2
cat lefthalf | head -n 15 | rev > q3
cat q2 q3 > lefthalfDONE
cat righthalf | tail -n 15 | rev > q1
cat righthalf | head -n 15 | rev > q4
cat q1 q4 > righthalfDONE
paste lefthalfDONE righthalfDONE -d X > almost
sed 's/X//g' almost > uka0.results
cat uka0.results



